services:
  # Development service
  app:
    container_name: a-board
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3004:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  # Database service
  db:
    image: postgres:17-alpine
    container_name: nestjs-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  # pgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db-data: